// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using President.Data;

namespace President.Data.Migrations
{
    [DbContext(typeof(PresidentContext))]
    [Migration("20190517185314_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("President.Domain.PresidentInfo", b =>
                {
                    b.Property<string>("PresidentName")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Birthplace");

                    b.Property<DateTime>("Deathday");

                    b.Property<string>("Deathplace");

                    b.HasKey("PresidentName");

                    b.ToTable("PresidentInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
